# Generated by Django 4.0.3 on 2022-03-13 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='age')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'actor and director',
                'verbose_name_plural': 'actors and directors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('tagline', models.CharField(max_length=100, verbose_name='tagline')),
                ('description', models.TextField(verbose_name='description')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='poster')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='year of premiered')),
                ('country', models.CharField(max_length=70, verbose_name='country')),
                ('world_premier', models.DateField(default=datetime.date.today, verbose_name='premierd_date')),
                ('budget', models.PositiveIntegerField(default=0, help_text='In dollars', verbose_name='budget')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='in dollars', verbose_name='fees in usa')),
                ('fees_over_world', models.PositiveIntegerField(default=0, help_text='in dollars', verbose_name='fees all over the world')),
                ('url', models.SlugField(unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='draft')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='main.actor', verbose_name='actorss')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='category')),
                ('directors', models.ManyToManyField(related_name='film_director', to='main.actor', verbose_name='directors')),
                ('genres', models.ManyToManyField(to='main.genre', verbose_name='genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='RatingStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip_address')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='movie')),
                ('stars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ratingstars', verbose_name='star')),
            ],
            options={
                'verbose_name': 'reyting',
                'verbose_name_plural': 'reytings',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('text', models.TextField(max_length=1500, verbose_name='message')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='movie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reviews', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Movieshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='image')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'Movieshot',
                'verbose_name_plural': 'Movieshots',
            },
        ),
    ]
